// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: dummmy/dummy.proto

package dummmy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDummyRequest) Reset() {
	*x = CreateDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDummyRequest) ProtoMessage() {}

func (x *CreateDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDummyRequest.ProtoReflect.Descriptor instead.
func (*CreateDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{0}
}

type CreateDummyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDummyReply) Reset() {
	*x = CreateDummyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDummyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDummyReply) ProtoMessage() {}

func (x *CreateDummyReply) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDummyReply.ProtoReflect.Descriptor instead.
func (*CreateDummyReply) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{1}
}

type UpdateDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDummyRequest) Reset() {
	*x = UpdateDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDummyRequest) ProtoMessage() {}

func (x *UpdateDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDummyRequest.ProtoReflect.Descriptor instead.
func (*UpdateDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{2}
}

type UpdateDummyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDummyReply) Reset() {
	*x = UpdateDummyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDummyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDummyReply) ProtoMessage() {}

func (x *UpdateDummyReply) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDummyReply.ProtoReflect.Descriptor instead.
func (*UpdateDummyReply) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{3}
}

type DeleteDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDummyRequest) Reset() {
	*x = DeleteDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDummyRequest) ProtoMessage() {}

func (x *DeleteDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDummyRequest.ProtoReflect.Descriptor instead.
func (*DeleteDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{4}
}

type DeleteDummyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDummyReply) Reset() {
	*x = DeleteDummyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDummyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDummyReply) ProtoMessage() {}

func (x *DeleteDummyReply) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDummyReply.ProtoReflect.Descriptor instead.
func (*DeleteDummyReply) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{5}
}

type GetDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDummyRequest) Reset() {
	*x = GetDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyRequest) ProtoMessage() {}

func (x *GetDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyRequest.ProtoReflect.Descriptor instead.
func (*GetDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{6}
}

type GetDummyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDummyReply) Reset() {
	*x = GetDummyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyReply) ProtoMessage() {}

func (x *GetDummyReply) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyReply.ProtoReflect.Descriptor instead.
func (*GetDummyReply) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{7}
}

type ListDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDummyRequest) Reset() {
	*x = ListDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDummyRequest) ProtoMessage() {}

func (x *ListDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDummyRequest.ProtoReflect.Descriptor instead.
func (*ListDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{8}
}

type ListDummyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDummyReply) Reset() {
	*x = ListDummyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummmy_dummy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDummyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDummyReply) ProtoMessage() {}

func (x *ListDummyReply) ProtoReflect() protoreflect.Message {
	mi := &file_dummmy_dummy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDummyReply.ProtoReflect.Descriptor instead.
func (*ListDummyReply) Descriptor() ([]byte, []int) {
	return file_dummmy_dummy_proto_rawDescGZIP(), []int{9}
}

var File_dummmy_dummy_proto protoreflect.FileDescriptor

var file_dummmy_dummy_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x75,
	0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75,
	0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xf9, 0x02, 0x0a, 0x05, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x12, 0x4b, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4b, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d,
	0x6d, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a,
	0x09, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x31, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x6d, 0x6d,
	0x6d, 0x79, 0x50, 0x01, 0x5a, 0x21, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79,
	0x3b, 0x64, 0x75, 0x6d, 0x6d, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dummmy_dummy_proto_rawDescOnce sync.Once
	file_dummmy_dummy_proto_rawDescData = file_dummmy_dummy_proto_rawDesc
)

func file_dummmy_dummy_proto_rawDescGZIP() []byte {
	file_dummmy_dummy_proto_rawDescOnce.Do(func() {
		file_dummmy_dummy_proto_rawDescData = protoimpl.X.CompressGZIP(file_dummmy_dummy_proto_rawDescData)
	})
	return file_dummmy_dummy_proto_rawDescData
}

var file_dummmy_dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dummmy_dummy_proto_goTypes = []interface{}{
	(*CreateDummyRequest)(nil), // 0: api.dummmy.CreateDummyRequest
	(*CreateDummyReply)(nil),   // 1: api.dummmy.CreateDummyReply
	(*UpdateDummyRequest)(nil), // 2: api.dummmy.UpdateDummyRequest
	(*UpdateDummyReply)(nil),   // 3: api.dummmy.UpdateDummyReply
	(*DeleteDummyRequest)(nil), // 4: api.dummmy.DeleteDummyRequest
	(*DeleteDummyReply)(nil),   // 5: api.dummmy.DeleteDummyReply
	(*GetDummyRequest)(nil),    // 6: api.dummmy.GetDummyRequest
	(*GetDummyReply)(nil),      // 7: api.dummmy.GetDummyReply
	(*ListDummyRequest)(nil),   // 8: api.dummmy.ListDummyRequest
	(*ListDummyReply)(nil),     // 9: api.dummmy.ListDummyReply
}
var file_dummmy_dummy_proto_depIdxs = []int32{
	0, // 0: api.dummmy.Dummy.CreateDummy:input_type -> api.dummmy.CreateDummyRequest
	2, // 1: api.dummmy.Dummy.UpdateDummy:input_type -> api.dummmy.UpdateDummyRequest
	4, // 2: api.dummmy.Dummy.DeleteDummy:input_type -> api.dummmy.DeleteDummyRequest
	6, // 3: api.dummmy.Dummy.GetDummy:input_type -> api.dummmy.GetDummyRequest
	8, // 4: api.dummmy.Dummy.ListDummy:input_type -> api.dummmy.ListDummyRequest
	1, // 5: api.dummmy.Dummy.CreateDummy:output_type -> api.dummmy.CreateDummyReply
	3, // 6: api.dummmy.Dummy.UpdateDummy:output_type -> api.dummmy.UpdateDummyReply
	5, // 7: api.dummmy.Dummy.DeleteDummy:output_type -> api.dummmy.DeleteDummyReply
	7, // 8: api.dummmy.Dummy.GetDummy:output_type -> api.dummmy.GetDummyReply
	9, // 9: api.dummmy.Dummy.ListDummy:output_type -> api.dummmy.ListDummyReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dummmy_dummy_proto_init() }
func file_dummmy_dummy_proto_init() {
	if File_dummmy_dummy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dummmy_dummy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDummyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDummyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDummyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummmy_dummy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDummyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dummmy_dummy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummmy_dummy_proto_goTypes,
		DependencyIndexes: file_dummmy_dummy_proto_depIdxs,
		MessageInfos:      file_dummmy_dummy_proto_msgTypes,
	}.Build()
	File_dummmy_dummy_proto = out.File
	file_dummmy_dummy_proto_rawDesc = nil
	file_dummmy_dummy_proto_goTypes = nil
	file_dummmy_dummy_proto_depIdxs = nil
}
